{
   "name": "nvidia-prometheus-exporter",
   "apiVersion": "0.0.1",
   "kind": "ksonnet.io/parts",
   "description": "Nvidia Prometheus GPU stats exporter\n",
   "author": "Cisco AI",
   "contributors": [
      {
         "name": "Adhita Selvaraj",
         "email": "adselvar@cisco.com"
      }
   ],
   "keywords": [
      "Nvidia",
      "GPUs",
      "Prometheus",
      "Monitoring"
   ],
   "license": "Apache 2.0"
}
